# Site settings
title: Wagner Lopes
twitter_username: wagnerl0pes
name: Wagner Luís Barbosa de Abreu Lopes

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: http://wagnerlopes.blogspot.com/
 - title: GitHub
   url: https://github.com/wagnerlopes
 - title: StackOverflow
   url: http://stackoverflow.com/users/7103811/wagner-lopes
 - title: DZone
   url: https://dzone.com/users/977271/wagnerluislopes.html
 - title: LinkedIn
   url: https://www.linkedin.com/in/wagnerluislopes

#Any buzzword skills you want to include
skills:
 - Spring MVC
 - Spring Boot
 - Struts 2
 - Java
 - JPA
 - Oracle
 - SQL
 - REST
 - Tech Architecture
 
#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: http://wagnerlopes.blogspot.com/feeds/posts/default

#Work experience is required
roles:
 - title: Senior Arch and Programmer
   start: 2001
   end: Ongoing
   employer: Brazilian Army
   description: Java Programmer.
 - title: Oracle Programmer
   start: 1995
   end: 2001
   employer: Brazilian Army
   description: Oracle PL/SQL Programmer.
 - title: Artillery Officer
   start: 1991
   end: 1995
   employer: Brazilian Army
   description: A range of functional and technical militaries roles.

#Education is required
education:
 - level: System Analysis and Development
   date: 1994
   school: Faculdades Associadas de São Paulo

#This section is optional (as is the image link below)
coursera:
   profileurl:
   courses:
    - title:
      link:
      optionalimage:
      date:

#List of interesting Github repo/projects to include - optional
github:
 - wagnerlopes/esculapio

#Stackoverflow flair is optional
stackoverflow:
   profileurl: http://stackoverflow.com/users/7103811/wagner-lopes
   flairimageurl: http://stackoverflow.com/users/flair/7103811.png

#Mobile apps section is optional
apps:
 - name: 
   platform:
   url: 
   description: 

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>JVM</strong>: I am experienced in a variety of Java API’s and frameworks. I have recently worked with Spring 4, Spring-security, JPA (EclipseLink) in addition to others. <br/><br/>
   <strong>Web Development</strong>: My server side web development experience has largely been based on the Struts 2 (and sometimes Spring MVC framework). I have also worked with some client side technology, having used jQuery, Bootstrap and Font Awesome.<br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git and Maven. I have experience with an array of testing tools and technologies.<br/><br/>
   I have also gained experience and knowledge in last twenty years working in enterprise projects. <br/><br/>
